### ISSUE TITLE
Geminiが生成する文章が長いと発生するバグ

### ISSUE THREAD

**Issue by Rustumi-Hinata** [konoka-iori/gemini-discord-bot#11]
## 概要

長い文章を生成しようとしたら発生したエラー
現状、Geminiが生成した文章の確認が取れていないので何とも言えない

## 不具合内容

```
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
```

## 再現手順

Geminiに長い文章を生成させれば、再現可能かもしれない

## 期待する動作

これらの対応を行えば期待通りの動作になるかもしれない
- 送信を2分割する
- 文書生成の長さをエラー内容以下にする

## 備考

言語がjavascriptですがバグ修正の方針の参考になりそうなサイトを貼っておきます

1. [字数制限を超えないように分けてメッセージを送信する](https://scrapbox.io/discordjs-japan/%E5%AD%97%E6%95%B0%E5%88%B6%E9%99%90%E3%82%92%E8%B6%85%E3%81%88%E3%81%AA%E3%81%84%E3%82%88%E3%81%86%E3%81%AB%E5%88%86%E3%81%91%E3%81%A6%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%82%92%E9%80%81%E4%BF%A1%E3%81%99%E3%82%8B)
2. [Embed Limits
](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits:~:text=should%20display%20inline-,Embed%20Limits,-To%20facilitate%20showing)

**Comment by konoka-iori** [comment]
報告ありがとうございます。
Embedの文字数制限にかかっていそう。
送信を分割する方向で修正してみたい。

**Comment by konoka-iori** [comment]
1025文字目からフィールド2に分割するのは一工夫すればできるけど、問題はEmbedのフィールド2の`name`をどうするか……これたしか必須だったので `Gemini-Proの回答（続き）` とか何かしら書かないとエラーになるかも。

**Comment by konoka-iori** [comment]
そもそもフィールドが変に分割されるので見やすさ的にはどうなんだ……という問題もある

**Comment by Rustumi-Hinata** [comment]
Geminiの文章の生成を規制した方が全体の文章としては見やすいし、対処は楽だよね

**Comment by konoka-iori** [comment]
うーん、Gemini側で1024に制限してみる方法で調整してみます

**Comment by konoka-iori** [comment]
```python
config = {"max_output_tokens": 1024}
gemini.configure(api_key=self.token)
model = gemini.GenerativeModel("gemini-pro", generation_config=config)
```
にしてみたけど普通に1024文字以上出てくる

**Comment by konoka-iori** [comment]
そういやトークン数と文字数は一致しないのか。
その場合1トークンが何文字になるのか調べなくてはいけないね

**Comment by konoka-iori** [comment]
`config = {"max_output_tokens": 1000}` としたらだいたい1000文字くらいで出力される。
確実に出力文字数を制御する方法が `max_output_tokens` しか見当たらないので、いったんこれである程度制御して溢れた分はBOT側の実装でカットするか

なにかいい方法があれば良いのですが

**Comment by konoka-iori** [comment]
とりあえずGemini側である程度制御するコードを追加
